//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reaper.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reaper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API is not online. Please try again later. ähnelt.
        /// </summary>
        public static string ApiOffline {
            get {
                return ResourceManager.GetString("ApiOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API is online ähnelt.
        /// </summary>
        public static string ApiOnline {
            get {
                return ResourceManager.GetString("ApiOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reaper ähnelt.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} v{1} ähnelt.
        /// </summary>
        public static string AppTitleFormat {
            get {
                return ResourceManager.GetString("AppTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} by {1} ähnelt.
        /// </summary>
        public static string BylineFormat {
            get {
                return ResourceManager.GetString("BylineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close {0} with error: {1} ähnelt.
        /// </summary>
        public static string CloseAppErrorFormat {
            get {
                return ResourceManager.GetString("CloseAppErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closed {0}. ähnelt.
        /// </summary>
        public static string CloseAppFormat {
            get {
                return ResourceManager.GetString("CloseAppFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continuing in standard mode ähnelt.
        /// </summary>
        public static string ContinuingStandardMode {
            get {
                return ResourceManager.GetString("ContinuingStandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die description ähnelt.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die       
        ///Your device is not connected to the internet.
        ///This application needs internet access.
        ///Please connect your device to the internet to use this application. ähnelt.
        /// </summary>
        public static string DeviceOfflineDetails {
            get {
                return ResourceManager.GetString("DeviceOfflineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device is online ähnelt.
        /// </summary>
        public static string DeviceOnline {
            get {
                return ResourceManager.GetString("DeviceOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WetterSenseDev ähnelt.
        /// </summary>
        public static string DevName {
            get {
                return ResourceManager.GetString("DevName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error found. ähnelt.
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error. Retype password ähnelt.
        /// </summary>
        public static string ErrorRetypePassword {
            get {
                return ResourceManager.GetString("ErrorRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///The following Exception was raised : {0} ähnelt.
        /// </summary>
        public static string ExceptionRaisedFormat {
            get {
                return ResourceManager.GetString("ExceptionRaisedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die afrikaans|albanian|arabic|azerbaijani|bulgarian|catalan|czech|danish|german|greek|english|basque|persian|farsi|finnish|french|galician|Hebrew|hindi|croatian|hungarian|indonesian|italian|japanese|korean|latvian|lithuanian|macedonian|norwegian|dutch|polish|portuguese|romanian|russian|swedish|slovak|slovenian|spanish|serbian|thai|turkish|ukrainian|vietnamese|chinese simplified|chinese traditional|zulu ähnelt.
        /// </summary>
        public static string FullySupportedLanguages {
            get {
                return ResourceManager.GetString("FullySupportedLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die highest temperature ähnelt.
        /// </summary>
        public static string highestTemp {
            get {
                return ResourceManager.GetString("highestTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die imperial ähnelt.
        /// </summary>
        public static string imperial {
            get {
                return ResourceManager.GetString("imperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid input. ähnelt.
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die local system time ähnelt.
        /// </summary>
        public static string localSystemTime {
            get {
                return ResourceManager.GetString("localSystemTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lowest temperature ähnelt.
        /// </summary>
        public static string lowestTemp {
            get {
                return ResourceManager.GetString("lowestTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your mail address ähnelt.
        /// </summary>
        public static string mailAddressQuery {
            get {
                return ResourceManager.GetString("mailAddressQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail powered by htmlemail.io &amp; {0} ähnelt.
        /// </summary>
        public static string MailPoweredByFormat {
            get {
                return ResourceManager.GetString("MailPoweredByFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mail sent successfully ähnelt.
        /// </summary>
        public static string mailSuccessMessage {
            get {
                return ResourceManager.GetString("mailSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want this as a mail? ähnelt.
        /// </summary>
        public static string mailWanted {
            get {
                return ResourceManager.GetString("mailWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die metric ähnelt.
        /// </summary>
        public static string metric {
            get {
                return ResourceManager.GetString("metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the name of the city which you want weather data of. ähnelt.
        /// </summary>
        public static string nameOfCity {
            get {
                return ResourceManager.GetString("nameOfCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter your name or type &quot;no&quot; to not be addressed (without quotes) ähnelt.
        /// </summary>
        public static string nameOr {
            get {
                return ResourceManager.GetString("nameOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network error contacting API: {0} ähnelt.
        /// </summary>
        public static string NetworkErrorFormat {
            get {
                return ResourceManager.GetString("NetworkErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no ähnelt.
        /// </summary>
        public static string NoOption {
            get {
                return ResourceManager.GetString("NoOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any key to exit. ähnelt.
        /// </summary>
        public static string PressAnyKeyExit {
            get {
                return ResourceManager.GetString("PressAnyKeyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press Enter to continue. ähnelt.
        /// </summary>
        public static string pressEnterContinue {
            get {
                return ResourceManager.GetString("pressEnterContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select your preferred language ähnelt.
        /// </summary>
        public static string SelectPreferredLanguage {
            get {
                return ResourceManager.GetString("SelectPreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the superuser password. Password won&apos;t be shown, type each char individually, backspace to correct, enter to continue ähnelt.
        /// </summary>
        public static string SuperUserPasswordPrompt {
            get {
                return ResourceManager.GetString("SuperUserPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to enter superuser mode? ähnelt.
        /// </summary>
        public static string SuperUserQuestion {
            get {
                return ResourceManager.GetString("SuperUserQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die af|al|ar|az|bg|ca|cz|da|de|el|en|eu|fa|fa|fi|fr|gl|he|hi|hr|hu|id|it|ja|kr|la|lt|mk|no|nl|pl|pt|pt_br|ro|ru|se|sk|sl|sr|th|tr|ua|vi|zh_cn|zh_tw|zu ähnelt.
        /// </summary>
        public static string SupportedShortCodes {
            get {
                return ResourceManager.GetString("SupportedShortCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die temperature ähnelt.
        /// </summary>
        public static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for using {0}! ähnelt.
        /// </summary>
        public static string ThankYouFormat {
            get {
                return ResourceManager.GetString("ThankYouFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The weather in ähnelt.
        /// </summary>
        public static string theWeatherIn {
            get {
                return ResourceManager.GetString("theWeatherIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time at destination ähnelt.
        /// </summary>
        public static string timeAtDestination {
            get {
                return ResourceManager.GetString("timeAtDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall of {0} failed with error: {1} ähnelt.
        /// </summary>
        public static string UninstallErrorFormat {
            get {
                return ResourceManager.GetString("UninstallErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to unistall {0}? ähnelt.
        /// </summary>
        public static string UninstallPromptFormat {
            get {
                return ResourceManager.GetString("UninstallPromptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the name of the unit system you want to use ähnelt.
        /// </summary>
        public static string unitQuery {
            get {
                return ResourceManager.GetString("unitQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0.9.1 ähnelt.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weather data powered by openweathermap.org ähnelt.
        /// </summary>
        public static string WeatherPoweredBy {
            get {
                return ResourceManager.GetString("WeatherPoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yes ähnelt.
        /// </summary>
        public static string YesOption {
            get {
                return ResourceManager.GetString("YesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die your weather info ähnelt.
        /// </summary>
        public static string yourWeatherInfo {
            get {
                return ResourceManager.GetString("yourWeatherInfo", resourceCulture);
            }
        }
    }
}
